apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:3f2951534266bc986600601e4bb95812d60342b274e59e58c123f8ef2f07e68b # replace with your index image
  displayName: Argo CD Operators
  publisher: Argo CD Community